container:
    registry:
        class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
        zkclient:
            class: kazoo.client:KazooClient
            hosts: 127.0.0.1:2181

    events:
        class: lymph.events.kombu:KombuEventSystem
        transport: amqp
        hostname: 127.0.0.1
    ip: 0.0.0.0    

instances:
    Web:
        command: lymph instance --config=conf/web.yml
        numprocesses: 1

sockets:
    Web:
        port: 4080
